{% set name = "yaqd-vici" %}
{% set version = "2021.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaqd-vici-{{ version }}.tar.gz
  sha256: d9d9954335cf819c155f63c0033b59d6e3b4316eb40d9abac9c1d94e9768132a

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-vici-two-position = yaqd_vici._vici_two_position:ViciTwoPosition.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit
    - pip
    - python >=3.7
  run:
    - pyserial
    - python >=3.7
    - yaqd-core >=2021.2.1

test:
  imports:
    - yaqd_vici
  commands:
    - pip check
    - yaqd-vici-two-position --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq support for VICI hardware
  dev_url: https://gitlab.com/yaq/yaqd-vici
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
